version: '3.4'

# See the following for this docker-compose setup
# https://www.reddit.com/r/csharp/comments/9cyl6a/debugging_dotnet_watch_processes_inside_of_a/
# https://natemcmaster.com/blog/2018/05/12/dotnet-watch-2.1/
# https://github.com/Dispersia/Dotnet-Watch-Docker-Example

services:
  vtram:
    container_name: generichost
    image: generichost/test
    build:
      context: .
    volumes:
      - './:/app'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - db
  # db:
  #   image: "microsoft/mssql-server-linux"
  #   ports:
  #     - "1433:1433"
  #   environment:
  #       SA_PASSWORD: "Password123!"
  #       ACCEPT_EULA: "Y"